// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbTgKk0VHoXqIcALfHjbxQldyh-VRE_Bg',
    appId: '1:451887675840:web:bd6b8bcc02d553c7a13025',
    messagingSenderId: '451887675840',
    projectId: 'hack-to-future',
    authDomain: 'hack-to-future.firebaseapp.com',
    storageBucket: 'hack-to-future.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2JCv4m5x_5f3N6Sour6BUPa-9lhCJ8UQ',
    appId: '1:451887675840:android:7d15992449ed8338a13025',
    messagingSenderId: '451887675840',
    projectId: 'hack-to-future',
    storageBucket: 'hack-to-future.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLuQ_L--Ovkzm94tF9Bz0EsehvjK7MUMU',
    appId: '1:451887675840:ios:11eb0a7d4adcb9fea13025',
    messagingSenderId: '451887675840',
    projectId: 'hack-to-future',
    storageBucket: 'hack-to-future.appspot.com',
    androidClientId: '451887675840-q1ivmsfla8hktgdhmq3vku9i8hmer8g0.apps.googleusercontent.com',
    iosClientId: '451887675840-k58ag0nrfran34cdjiiiu0vusae9irb8.apps.googleusercontent.com',
    iosBundleId: 'com.example.wavySellersApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLuQ_L--Ovkzm94tF9Bz0EsehvjK7MUMU',
    appId: '1:451887675840:ios:11eb0a7d4adcb9fea13025',
    messagingSenderId: '451887675840',
    projectId: 'hack-to-future',
    storageBucket: 'hack-to-future.appspot.com',
    androidClientId: '451887675840-q1ivmsfla8hktgdhmq3vku9i8hmer8g0.apps.googleusercontent.com',
    iosClientId: '451887675840-k58ag0nrfran34cdjiiiu0vusae9irb8.apps.googleusercontent.com',
    iosBundleId: 'com.example.wavySellersApp',
  );
}
